import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import { TanstackProvider } from "@/tanstack/tanstack-provider";
import { CartDrawer } from "@/components/drawer/cart-drawer/cart-drawer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <TanstackProvider>
            {children}
            <CartDrawer />
          </TanstackProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
