import { ICON } from "@/constants/icon";
import { FacebookIcon } from "@/constants/icons/facebook";
import { InstagramIcon } from "@/constants/icons/instagram";
import { LinkedInIcon } from "@/constants/icons/linkedin";
import { TwitterIcon } from "@/constants/icons/twitter";

export const footerNav = [
  {
    title: "Shop",
    navs: [
      {
        name: "Chicken",
        link: "",
      },
      {
        name: "Beef",
        link: "",
      },
      {
        name: "Goat",
        link: "",
      },
      {
        name: "Speciality Meats",
        link: "",
      },
      {
        name: "Sale Items",
        link: "",
      },
      {
        name: "Best Sellers",
        link: "",
      },
    ],
  },
  {
    title: "Resources",
    navs: [
      {
        name: "Cooking Tips",
        link: "",
      },
      {
        name: "Recipes",
        link: "",
      },
      {
        name: "Meat Handling Guidelines",
        link: "",
      },
      {
        name: "FAQs",
        link: "",
      },
    ],
  },
  {
    title: "Account",
    navs: [
      {
        name: "Sign In",
        link: "",
      },
      {
        name: "Create Account",
        link: "",
      },
      {
        name: "Order History",
        link: "",
      },
    ],
  },
  {
    title: "Customer Service",
    navs: [
      {
        name: "Contact Us",
        link: "",
      },
      {
        name: "Order Tracking",
        link: "",
      },
      {
        name: "Returns & Refunds",
        link: "",
      },
      {
        name: "Shipping Information",
        link: "",
      },
    ],
  },
  {
    title: "About Us",
    socials: [
      {
        icon: <FacebookIcon />,
      },
      {
        icon: <InstagramIcon />,
      },
      {
        icon: <LinkedInIcon />,
      },
      {
        icon: <TwitterIcon />,
      },
    ],
    navs: [
      {
        name: "Our Story",
        link: "",
      },
      {
        name: "Quality Commitment",
        link: "",
      },
      {
        name: "Meet Our Experts",
        link: "",
      },
    ],
  },
];

export type ICollapseData = {
  key: string;
  label: string;
  children: React.ReactNode;
};

export const collapseData: ICollapseData[] = [
  {
    key: "faq1",
    label: "Is the chicken breast fresh or frozen?",
    children: (
      <p className="bg-white w-full h-full ">
        Our chicken breast is delivered fresh, never frozen, to ensure the best
        quality and flavour.
      </p>
    ),
  },
  {
    key: "faq2",
    label: "How should I store chicken breast after delivery?",
    children: <p className="">hi</p>,
  },
  {
    key: "faq3",
    label: "How long does it take to cook chicken breast?",
    children: <p className="">hi</p>,
  },
  {
    key: "faq4",
    label: "Are your chicken breasts free from hormones and antibiotics?",
    children: <p className="">hi</p>,
  },
];

export const collapseData2: ICollapseData[] = [
  {
    key: "faq5",
    label: "How long does it take to cook chicken breast?",
    children: (
      <p className="">
        Yes, all our chicken is free from added hormones and antibiotics,
        sourced from trusted farms.
      </p>
    ),
  },
  {
    key: "faq6",
    label: "What is the weight of each chicken breast?",
    children: (
      <p className="md:text-[20px] text-[1rem] text-ash_400 md:leading-[2rem] leading-[1.5rem] md:tracking-[-0.025rem] tracking-[-0.02rem]">
        hi
      </p>
    ),
  },
  {
    key: "faq7",
    label: "Do you offer organic chicken breast?",
    children: (
      <p className="md:text-[20px] text-[1rem] text-ash_400 md:leading-[2rem] leading-[1.5rem] md:tracking-[-0.025rem] tracking-[-0.02rem]">
        hi
      </p>
    ),
  },
];

export const countries: { name: string; country_code: string }[] = [
  { name: "Nigeria", country_code: "NG" },
];

export const states: { [key: string]: { name: string; state_code: string }[] } =
  {
    Nigeria: [
      { name: "Abia State", state_code: "AB" },
      { name: "Adamawa State", state_code: "AD" },
      { name: "Akwa Ibom State", state_code: "AK" },
      { name: "Anambra State", state_code: "AN" },
      { name: "Bauchi State", state_code: "BA" },
      { name: "Bayelsa State", state_code: "BY" },
      { name: "Benue State", state_code: "BE" },
      { name: "Borno State", state_code: "BO" },
      { name: "Cross River State", state_code: "CR" },
      { name: "Delta State", state_code: "DE" },
      { name: "Ebonyi State", state_code: "EB" },
      { name: "Edo State", state_code: "ED" },
      { name: "Ekiti State", state_code: "EK" },
      { name: "Enugu State", state_code: "EN" },
      { name: "Federal Capital Territory", state_code: "FC" },
      { name: "Gombe State", state_code: "GO" },
      { name: "Imo State", state_code: "IM" },
      { name: "Jigawa State", state_code: "JI" },
      { name: "Kaduna State", state_code: "KD" },
      { name: "Kano State", state_code: "KN" },
      { name: "Katsina State", state_code: "KT" },
      { name: "Kebbi State", state_code: "KE" },
      { name: "Kogi State", state_code: "KO" },
      { name: "Kwara State", state_code: "KW" },
      { name: "Lagos State", state_code: "LA" },
      { name: "Nasarawa State", state_code: "NA" },
      { name: "Niger State", state_code: "NI" },
      { name: "Ogun State", state_code: "OG" },
      { name: "Ondo State", state_code: "ON" },
      { name: "Osun State", state_code: "OS" },
      { name: "Oyo State", state_code: "OY" },
      { name: "Plateau State", state_code: "PL" },
      { name: "Sokoto State", state_code: "SO" },
      { name: "Taraba State", state_code: "TA" },
      { name: "Yobe State", state_code: "YO" },
      { name: "Zamfara State", state_code: "ZA" },
    ],
  };

export const cities = {
  "Abia State": [
    "Aba",
    "Amaigbo",
    "Arochukwu",
    "Bende",
    "Ohafia-Ifigh",
    "Umuahia",
  ],
  "Adamawa State": [
    "Ganye",
    "Gombi",
    "Holma",
    "Jimeta",
    "Madagali",
    "Mayo-Belwa",
    "Mubi",
    "Ngurore",
    "Numan",
    "Toungo",
    "Yola",
  ],
  "Akwa Ibom State": ["Eket", "Esuk Oron", "Ikot Ekpene", "Itu", "Uyo"],
  "Anambra State": [
    "Agulu",
    "Atani",
    "Awka",
    "Enugu-Ukwu",
    "Igbo-Ukwu",
    "Ihiala",
    "Nkpor",
    "Nnewi",
    "Onitsha",
    "Ozubulu",
    "Uga",
    "Uruobo-Okija",
  ],
  "Bauchi State": [
    "Azare",
    "Bauchi",
    "Boi",
    "Bununu",
    "Darazo",
    "Dass",
    "Dindima",
    "Disina",
    "Gabarin",
    "Gwaram",
    "Kari",
    "Lame",
    "Lere",
    "Madara",
    "Misau",
    "Sade",
    "Yamrat",
    "Yanda Bayo",
    "Yuli",
    "Zadawa",
    "Zalanga",
  ],
  "Bayelsa State": ["Amassoma", "Twon-Brass", "Yenagoa"],
  "Benue State": [
    "Aliade",
    "Boju",
    "Igbor",
    "Makurdi",
    "Ochobo",
    "Otukpa",
    "Takum",
    "Ugbokpo",
    "Yandev",
    "Zaki Biam",
  ],
  "Borno State": [
    "Bama",
    "Benisheikh",
    "Biu",
    "Bornu Yassu",
    "Damasak",
    "Damboa",
    "Dikwa",
    "Gamboru",
    "Gwoza",
    "Kukawa",
    "Magumeri",
    "Maiduguri",
    "Marte",
    "Miringa",
    "Monguno",
    "Ngala",
    "Shaffa",
    "Shani",
    "Tokombere",
    "Uba",
    "Wuyo",
    "Yajiwa",
  ],
  "Cross River State": ["Akankpa", "Calabar", "Gakem", "Ikang", "Ugep"],
  "Delta State": [
    "Abraka",
    "Agbor",
    "Asaba",
    "Bomadi",
    "Burutu",
    "Kwale",
    "Obiaruku",
    "Ogwashi-Uku",
    "Orerokpe",
    "Patani",
    "Sapele",
    "Ughelli",
    "Umunede",
    "Warri",
  ],
  "Ebonyi State": ["Abakaliki", "Afikpo", "Effium", "Ezza-Ohu", "Isieke"],
  "Edo State": [
    "Agenebode",
    "Auchi",
    "Benin City",
    "Ekpoma",
    "Igarra",
    "Illushi",
    "Siluko",
    "Ubiaja",
    "Uromi",
  ],
  "Ekiti State": [
    "Ado-Ekiti",
    "Aramoko-Ekiti",
    "Efon-Alaaye",
    "Emure-Ekiti",
    "Ifaki",
    "Igbara-Odo",
    "Igede-Ekiti",
    "Ijero-Ekiti",
    "Ikere-Ekiti",
    "Ipoti",
    "Ise-Ekiti",
    "Oke Ila",
    "Omuo-Ekiti",
  ],
  "Enugu State": [
    "Adani",
    "Ake-Eze",
    "Aku",
    "Amagunze",
    "Awgu",
    "Eha Amufu",
    "Enugu",
    "Enugu-Ezike",
    "Ete",
    "Ikem",
    "Mberubu",
    "Nsukka",
    "Obolo-Eke (1)",
    "Opi",
    "Udi",
  ],
  "Federal Capital Territory": ["Abuja", "Kuje", "Kwali", "Madala"],
  "Gombe State": [
    "Akko",
    "Bara",
    "Billiri",
    "Dadiya",
    "Deba",
    "Dukku",
    "Garko",
    "Gombe",
    "Hinna",
    "Kafarati",
    "Kaltungo",
    "Kumo",
    "Nafada",
    "Pindiga",
  ],
  "Imo State": ["Iho", "Oguta", "Okigwe", "Orlu", "Orodo", "Owerri"],
  "Jigawa State": [
    "Babura",
    "Birnin Kudu",
    "Birniwa",
    "Dutse",
    "Gagarawa",
    "Gumel",
    "Gwaram",
    "Hadejia",
    "Kafin Hausa",
    "Kazaure",
    "Kiyawa",
    "Mallammaduri",
    "Ringim",
    "Samamiya",
  ],
  "Kaduna State": [
    "Anchau",
    "Burumburum",
    "Dutsen Wai",
    "Hunkuyi",
    "Kachia",
    "Kaduna",
    "Kafanchan",
    "Kagoro",
    "Kajuru",
    "Kujama",
    "Lere",
    "Mando",
    "Saminaka",
    "Soba",
    "Sofo-Birnin-Gwari",
    "Zaria",
  ],
  "Kano State": ["Dan Gora", "Gaya", "Kano"],
  "Katsina State": [
    "Danja",
    "Dankama",
    "Daura",
    "Dutsin-Ma",
    "Funtua",
    "Gora",
    "Jibia",
    "Jikamshi",
    "Kankara",
    "Katsina",
    "Mashi",
    "Ruma",
    "Runka",
    "Wagini",
  ],
  "Kebbi State": [
    "Argungu",
    "Bagudo",
    "Bena",
    "Bin Yauri",
    "Birnin Kebbi",
    "Dabai",
    "Dakingari",
    "Gulma",
    "Gwandu",
    "Jega",
    "Kamba",
    "Kangiwa",
    "Kende",
    "Mahuta",
    "Maiyama",
    "Shanga",
    "Wasagu",
    "Zuru",
  ],
  "Kogi State": [
    "Abocho",
    "Adoru",
    "Ankpa",
    "Bugana",
    "Dekina",
    "Egbe",
    "Icheu",
    "Idah",
    "Isanlu-Itedoijowa",
    "Kabba",
    "Koton-Karfe",
    "Lokoja",
    "Ogaminana",
    "Ogurugu",
    "Okene",
  ],
  "Kwara State": [
    "Ajasse Ipo",
    "Bode Saadu",
    "Gwasero",
    "Ilorin",
    "Jebba",
    "Kaiama",
    "Lafiagi",
    "Offa",
    "Okuta",
    "Omu-Aran",
    "Patigi",
    "Suya",
    "Yashikera",
  ],
  "Lagos State": [
    "Apapa",
    "Badagry",
    "Ebute Ikorodu",
    "Ejirin",
    "Epe",
    "Ikeja",
    "Lagos",
    "Lekki",
    "Ikorodu",
    "Ojo",
    "Makoko",
  ],
  "Nasarawa State": ["Buga", "Doma", "Keffi", "Lafia", "Nasarawa", "Wamba"],
  "Niger State": [
    "Auna",
    "Babana",
    "Badeggi",
    "Baro",
    "Bokani",
    "Duku",
    "Ibeto",
    "Konkwesso",
    "Kontagora",
    "Kusheriki",
    "Kuta",
    "Lapai",
    "Minna",
    "New Shagunnu",
    "Suleja",
    "Tegina",
    "Ukata",
    "Wawa",
    "Zungeru",
  ],
  "Ogun State": [
    "Abeokuta",
    "Ado Odo",
    "Idi Iroko",
    "Ifo",
    "Ijebu-Ife",
    "Ijebu-Igbo",
    "Ijebu-Ode",
    "Ilaro",
    "Imeko",
    "Iperu",
    "Isara",
    "Owode",
  ],
  "Ondo State": [
    "Agbabu",
    "Akure",
    "Idanre",
    "Ifon",
    "Ilare",
    "Ode",
    "Ondo",
    "Ore",
    "Owo",
  ],
  "Osun State": [
    "Apomu",
    "Ejigbo",
    "Gbongan",
    "Ijebu-Jesa",
    "Ikire",
    "Ikirun",
    "Ila Orangun",
    "Ile-Ife",
    "Ilesa",
    "Ilobu",
    "Inisa",
    "Iwo",
    "Modakeke",
    "Oke Mesi",
    "Olupona",
    "Osogbo",
    "Otan Ayegbaju",
    "Oyan",
  ],
  "Oyo State": [
    "Ago Are",
    "Alapa",
    "Fiditi",
    "Ibadan",
    "Igbeti",
    "Igbo-Ora",
    "Igboho",
    "Kisi",
    "Lalupon",
    "Ogbomoso",
    "Okeho",
    "Orita Eruwa",
    "Oyo",
    "Saki",
  ],
  "Plateau State": [
    "Amper",
    "Bukuru",
    "Dengi",
    "Jos",
    "Kwolla",
    "Langtang",
    "Pankshin",
    "Panyam",
    "Vom",
    "Yelwa",
  ],
  "Sokoto State": [
    "Binji",
    "Dange",
    "Gandi",
    "Goronyo",
    "Gwadabawa",
    "Illela",
    "Rabah",
    "Sokoto",
    "Tambuwal",
    "Wurno",
  ],
  "Taraba State": [
    "Baissa",
    "Beli",
    "Gassol",
    "Gembu",
    "Ibi",
    "Jalingo",
    "Lau",
    "Mutum Biyu",
    "Riti",
    "Wukari",
  ],
  "Yobe State": [
    "Damaturu",
    "Dankalwa",
    "Dapchi",
    "Daura",
    "Fika",
    "Gashua",
    "Geidam",
    "Goniri",
    "Gorgoram",
    "Gujba",
    "Gwio Kura",
    "Kumagunnam",
    "Lajere",
    "Machina",
    "Nguru",
    "Potiskum",
  ],
  "Zamfara State": [
    "Anka",
    "Dan Sadau",
    "Gummi",
    "Gusau",
    "Kaura Namoda",
    "Kwatarkwashi",
    "Maru",
    "Moriki",
    "Sauri",
    "Tsafe",
  ],
  Rivers: [
    "Port Harcourt",
    "Obio-Akpor",
    "Eleme",
    "Oyigbo",
    "Ikwerre",
    "Emohua",
    "Etche",
    "Gokana",
    "Khana",
    "Tai",
    "Ogu–Bolo",
    "Andoni",
    "Bonny",
    "Degema",
    "Asari-Toru",
    "Akuku-Toru",
    "Okrika",
    "Ahoada East",
    "Ahoada West",
    "Omuma",
    "Ikwerre",
    "Ogba–Egbema–Ndoni",
    "Opobo–Nkoro",
    "Ikwerre",
    "Abua–Odual",
    "Okrika",
    "Oyigbo",
    "Tai",
    "Akuku-Toru",
    "Andoni",
    "Khana",
    "Gokana",
    "Eleme",
    "Obio-Akpor",
    "Port Harcourt",
    "Bonny",
    "Degema",
    "Asari-Toru",
    "Opobo–Nkoro",
    "Ikwerre",
    "Ahoada East",
    "Ahoada West",
    "Omuma",
    "Ogba–Egbema–Ndoni",
    "Abua–Odual",
  ],
};

export const dashboardCard = [
  {
    title: "Total revenue",
    filter: "1 year",
    amount: 20372550,
    type: "cur",
    icon: ICON.BarChartIcon,
  },
  {
    title: "Pending orders",
    filter: "Today",
    amount: 17,
    icon: ICON.LoaderIcon,
  },
  {
    title: "Completed orders",
    filter: "Today",
    amount: 83,
    icon: ICON.CheckCircleIcon,
  },
];

export const renderCustomerCard = (data: {
  totalOrders: number;
  totalProcessing: number;
  totalAmount: number;
}) => [
  {
    title: "Total number of orders",
    filter: "All Time",
    amount: data.totalOrders,
    icon: ICON.BarChartIcon,
  },
  {
    title: "Orders in progress",
    filter: "All Time",
    amount: data.totalProcessing,
    icon: ICON.LoaderIcon,
  },
  {
    title: "Total Amount Spent",
    filter: "All Time",
    amount: data.totalAmount,
    type: "cur",
    icon: ICON.CheckCircleIcon,
  },
];
